### ISSUE TITLE
Feature Request: support for Flex v2

### ISSUE THREAD

**Issue by maurice-ttp** [twilio/terraform-provider-twilio#121]
### Issue Summary
Now that Flex v2 [is officially in GA](https://www.twilio.com/changelog/flex-ui-20-is-now-in-ga), it would be awesome to have support for this new production version + the conversation API

**Comment by rakatyal** [comment]
Hi @maurice-ttp, I believe this is a work in progress on the product API side. In order to properly track this feature request, please [file a support ticket](https://twilio.com/help/contact)
